name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        run: |
          echo "Set up JDK 17 with Temurin"
          curl -L -o temurin.tar.gz https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.0%2B35/OpenJDK17U-jdk_x64_linux_hotspot_17.0.0_35.tar.gz
          tar xzf temurin.tar.gz
          export JAVA_HOME=$PWD/jdk-17.0.0+35
          export PATH=$JAVA_HOME/bin:$PATH

      - name: Build with Maven
        run: mvn -B clean package

      - name: Execute Jar File
        run: |
          sudo kill -9 $(sudo lsof -t -i:80) || true
          nohup sudo java -jar /home/ubuntu/actions-runner/_work/ADBMS-Mini-project/ADBMS-Mini-project/target/hostal-0.0.1-SNAPSHOT.jar &
